### ISSUE TITLE
Documentation on physical layer?

### ISSUE THREAD

**Issue by ekiwi** [arachnidlabs/uCAN#1]
Hi,

I am working on a uC board (for either the _STM32F072C8_ or the _STM32F042C4_) with on board CAN transceiver and would like to provide the necessary connections in order to be able to connect to a uCAN network besides my own connector.

Unfortunately I was not able to find any good documentation on the physical layer, i.e. the stuff I need to know in order to build compatible hardware.
Is there any available?

From the schematics I can tell that:
- **Pin1** is `CANH`
- **Pin2** is `CANL`
- **Pin4/5** are `VCC`
- **Pin7/8** are `GND`

But what is the maximum VCC at the Injector? What is the maximum voltage drop over the wires that one should account for?

Also I haven't been able to quite figure out what **PIN3** and **PIN6** are meant for.

Maybe you can add this information to the uCAN repository.

Thanks!

Kevin

**Comment by bartv** [comment]
https://github.com/arachnidlabs/uCAN/wiki/Physical-layer

**Comment by Arachnid** [comment]
Let me know if there's anything you need that isn't in bartv's link.
